name: Build and upload
 
on:
 workflow_dispatch:

env:
  HOMEBREW_FFMPEG_VERSION: 5
  FFMPEG_VERSION: 5.1.2
 
jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: | 
          brew install SDL2
          brew install ffmpeg@${{ env.HOMEBREW_FFMPEG_VERSION }}
          brew install mingw-w64
          brew install wget

      - name: Build for Apple Silicon
        run: cd fftools && make libavutil/ffversion.h config build

      - name: Build for Windows x64
        run: cd fftools && make libavutil/ffversion.h win_64_get_dependencies win_64_config win_64_build

      - name: Zip release
        run: zip -r fftools/ffpatched_win64_arm64.zip fftools/ffpatched_win64 fftools/ffpatched_arm64

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.FFMPEG_VERSION }}
          release_name: Release ${{ env.FFMPEG_VERSION }}
          draft: false
          prerelease: false

      - name: Upload release artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: fftools/ffpatched_win64_arm64.zip
          asset_name: ffpatched_win64_arm64.zip
          asset_content_type: application/octet-stream